# Видео
video_path: "sample1.mp4"
video_sizer: 0.4
show_video: True

# Логирование
log_file: "logs/tracking.log"
log_level: "DEBUG"
log_format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS!UTC} UTC+00:00</> | \
             <level>{level: <8}</> | \
             <yellow>PID={process:07d}</> | \
             <cyan>{name}:{function}:{line}</> - <level>{message}</>"

# Сетевое взаимодействие
network:
  using: Placeholder

  Placeholder: {}

  BackendSender:
    domain_url: 127.0.0.1

# Детектирование
detection:
  using: Background

  Background: {}

# Трекинг
tracking:
  using: Centroid

  Centroid: {}
