scanning:
  # источник видео. Может быть файлом, url'ом или чем-либо ещё
  video_path: "sample.mp4"

  # отображать видео во время работы программы
  show_video: True

  # автоматически начинать воспроизведение заново в случае утери соединения
  # или окончании видеофайла (начнёт вопроизводиться с начала)
  auto_restart: True

  # распознавание пачек
  recognizing:
    using: "Background"

    # распознавание пачек на основании фона
    Background:
      # кол-во срабатываний, которое необходимо для активации
      activation:
        upper_bound: 15
        lower_bound: -20

      # пережатие изображения для ускорения
      sizer: 1.0
      # скорость переобучения фона
      learning_rate: 0.0001
      # пороговое значение активации
      threshold_score: 0.65

      # область для распознавания (обычно в некоторых частях кадров больше шумов и постороннего движения)
      # не влияет на чтение QR-кодов - они продолжают определяться по всему изображению
      region:
        x1: 0.0
        x2: 1.0
        y1: 0.8
        y2: 1.0

    # распознавание пачек нейросетью
    Neuronet:
      model_path: "model.tflite"
      threshold_score: 0.8

    # распознавание пачек сенсором
    Sensor:
      sensor_ip: "192.168.1.1"
      sensor_const: ".1.3.6.1.4.1.40418.2.6.2.2.1.3.1.4"
      # как часто (раз в сколько кадров?) будет срабатывать проверка
      skipframes_mod: 30

  # сохранение изображений или видео для анализа
  images_logging:
    using: "SaveImages"

    # не сохраняет ничего
    No: {}

    # сохраняет до 50 картинок на каждую пачку без кодов
    SaveImages:
      path: "./pics"
      buff_size: 50
      sizer: 0.3

networking:
  log_path: "logs/networking.log"
  log_level: "INFO"

  commutication:
    using: "OnlySendCodes"

    # Отправлять некорректные коды серверу без сбрасывания заслонкой
    OnlySendCodes:
      domain: "192.168.1.1"

    # Сбрасывать заслонкой некорректные пачки, отправляя серверу коды
    DropAndSendCodes:
      domain: "localhost"
      shutter_ip: "192.168.1.2"
      shutter_const: '.1.3.6.1.4.1.40418.2.6.2.2.1.3.1.2'
      shutter_wait_before_sec: 8
      shutter_wait_open_sec: 25

    # Сбрасывать заслонкой некорректные пачки, не извещая о них сервер
    DropOnly:
      domain: "localhost"
      shutter_ip: "192.168.1.2"
      shutter_const: '.1.3.6.1.4.1.40418.2.6.2.2.1.3.1.2'
      shutter_wait_before_sec: 8
      shutter_wait_open_sec: 25

  packs_synchronization:
    using: "FillPlaceholders"

    # Дописывает заглушки вместо недостающих пачек и помечает их неккоректными
    FillPlaceholders: {}